# Generated by Django 2.0.6 on 2018-06-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180619_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='roles',
        ),
    ]
