# Generated by Django 2.0.6 on 2018-06-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180619_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
