# Generated by Django 2.0.6 on 2018-06-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
