# Generated by Django 2.0.6 on 2018-06-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('employee_medicare', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('employee_social_security', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('employer_medicare', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('employer_social_security', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('futa', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('wa_uta', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('gross_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_paystubs', to='profiles.Profile')),
            ],
            options={
                'ordering': ('-pay_period_start',),
                'permissions': (('approve_payroll', 'Approve Payroll'),),
            },
        ),
    ]
