# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('hours', models.FloatField()),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField()),
                ('medicare', models.FloatField(blank=True, null=True)),
                ('social_security', models.FloatField(blank=True, null=True)),
                ('futa', models.FloatField(blank=True, null=True)),
                ('wa_uta', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-pay_period_start',),
            },
        ),
    ]
