# Generated by Django 2.0.6 on 2018-06-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20180620_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='medicare',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='social_security',
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee_medicare',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee_social_security',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='employer_medicare',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='employer_social_security',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employee_paystubs', to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='futa',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='wa_uta',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
