# Generated by Django 2.0.6 on 2018-06-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20180620_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='employee_medicare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee_social_security',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employer_medicare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employer_social_security',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='futa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='wa_uta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
