# Generated by Django 2.0.6 on 2018-06-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20180620_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
