# Generated by Django 2.0.6 on 2018-06-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payroll_gross_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ('-pay_period_start',), 'permissions': (('approve_payroll', 'Approve Payroll'),)},
        ),
    ]
