# Generated by Django 2.0.6 on 2018-06-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payroll_current_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='current_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
